version: '3'
volumes:
  cert-intelmq-bots-output:
    driver: local
  cert-intelmq-bots:
    driver: local
  cert-intelmq-logs:
    driver: local
  cert-intelmq-redis:
    driver: local
  cert-intelmq-elastic-data:
    driver: local
  cert-intelmq-grafana:
    driver: local

networks:
  intelmq-network:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.routing.allocation.disk.threshold_enabled: 'false'
      discovery.type: single-node
      search.max_buckets: '10002'
    volumes:
    - cert-intelmq-elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - intelmq-network
  grafana:
    image: grafana/grafana:6.5.2
    volumes:
    - cert-intelmq-grafana:/var/lib/grafana
    links:
    - elasticsearch:elasticsearch
    user: '0'
    ports:
      - 3000:3000
    networks:
      - intelmq-network
  intelmq:
    build: intelmq/
    ports:
        - 8081:80
    depends_on:
      - redis
    networks:
      - intelmq-network
    volumes:
      - ./volumes/output/:/opt/intelmq/var/lib/bots/file-output/
      - ./volumes/logs:/opt/intelmq/var/log/
      # git clone yourRepo volumes/intelmq-bots git clone https://github.com/CERTUNLP/intelmq-bots.git volumes/intelmq-bots
      - ./volumes/intelmq-bots/etc:/opt/intelmq/etc
      - ./volumes/intelmq-bots/bots/BOTS:/opt/intelmq/etc/BOTS
      - ./volumes/intelmq-bots/:/intelmq-bots/
    environment:
      REDIS_SERVER: redis
      DEV: "true"
      LOG_MAIL_ENABLED: "true"
      LOG_MAIL_LEVEL: "logging.ERROR"
      LOG_MAIL_MAILHOST: "mail.example.unlp.edu.ar"
      LOG_MAIL_PORT: 25
      LOG_MAIL_FROMADDR: "intelmq@examplefeeds.unlp.edu.ar"
      LOG_MAIL_TOADDR: "support@example.unlp.edu.ar"
      LOG_MAIL_SUBJECT: "[INTELMQ] Application Error"
      LOG_MAIL_CREDENTIALS: None #tuple (username, password)
      LOG_MAIL_SECURE: None
      ENABLE_BOTNET_AT_BOOT: "true"
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      - intelmq-network
  logrotate:
    image: blacklabelops/logrotate
    environment:
      LOGS_DIRECTORIES: /var/log/intelmq
      LOGROTATE_COPIES: '3'
      LOGROTATE_SIZE: 100M
      LOGROTATE_COMPRESSION: compress
      LOGROTATE_CRONSCHEDULE: '46 * * * * *'
    volumes:
    - ./volumes/logs:/var/log/intelmq
