{
 "title": "GREPUNLP Web Elasticsearch",
 "description": "Browse, analyze logs in Elasticsearchstatus_codes, pie-chart, top 10 clientip, line-chart,word-map and etc...",
 "tags": [
  "nginx",
  "es",
  "logstash",
  "log"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "域名",
    "query": "{\"find\":\"terms\",\"field\":\"domain.keyword\"}"
   },
   {
    "name": "status",
    "label": "状态码",
    "query": "{\"find\":\"terms\",\"field\":\"status\"}"
   },
   { "name": "responsetime", "label": "请求时间", "query": "1,2,3,4,5,10" },
   {
    "name": "inter",
    "label": "周期",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "$domain 所有接口平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "responsetime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "domain:$domain AND  upstreamaddr:\"unix:/usr/local/php/var/run/php-fpm.sock\" and user_agent!='MSIE' and user_agent!='Zabbix'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response HTTP codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extra.response_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "time.observation", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time.observation"
    }
   ]
  },
  {
   "title": "Most common response Titles",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extra.title.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "time.observation", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time.observation"
    }
   ]
  },
  {
   "title": "Top ten Server Header",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extra.headers.Server.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "time.observation", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time.observation"
    }
   ]
  },
  {
   "title": "$domain 访问前十的省份",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.region_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain 国家/地区访问占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain 请求方法占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain 访问前十的城市",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$domain Word Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain referer top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain user_agent top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_user_agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "历史趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "$domain 请求数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP 状态码",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none", "label": "状态码数量" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain 慢响应 时间>$responsetime s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND responsetime:[$responsetime TO 100] and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "$domain status:$status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "domain:$domain and status:$status and user_agent!=MSIE",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}